CREATE TABLE members
(
    `id`                        bigint NOT NULL AUTO_INCREMENT,
    `barcode_id`                varchar(12) UNIQUE DEFAULT NULL,
    `last_name`                 varchar(50)        DEFAULT NULL,
    `first_name`                varchar(50)        DEFAULT NULL,
    `middle_name`               varchar(50)        DEFAULT NULL,
    `suffix`                    varchar(5)         DEFAULT NULL,
    `short_name`                varchar(50)        DEFAULT NULL,
    `address`                   varchar(255)       DEFAULT NULL,
    `city`                      varchar(50)        DEFAULT NULL,
    `state`                     varchar(50)        DEFAULT NULL,
    `zip`                       int                DEFAULT NULL,
    `country_id`                smallint           DEFAULT NULL,
    `home_phone`                varchar(50)        DEFAULT NULL,
    `work_phone`                varchar(50)        DEFAULT NULL,
    `cellular`                  varchar(50)        DEFAULT NULL,
    `email`                     varchar(50)        DEFAULT NULL,
    `date_of_birth`             datetime           DEFAULT NULL,
    `marital_status`            varchar(50)        DEFAULT NULL,
    `member_status`             varchar(20)        DEFAULT NULL,
    `gender`                    varchar(50)        DEFAULT NULL,
    `religion`                  varchar(50)        DEFAULT NULL,
    `education_id`              int                DEFAULT 1,
    `degree`                    varchar(50)        DEFAULT NULL,
    `illness`                   varchar(50)        DEFAULT NULL,
    `physical_limitations`      varchar(150)       DEFAULT NULL,
    `dietary_requirements`      varchar(150)       DEFAULT NULL,
    `dietary_requirements_desc` varchar(200)       DEFAULT NULL,
    `date_adorer`               datetime           DEFAULT NULL,
    `date_hirang`               datetime           DEFAULT NULL,
    `date_council`              datetime           DEFAULT NULL,
    `is_active`                 boolean            DEFAULT TRUE,
    `date_created`              timestamp          DEFAULT CURRENT_TIMESTAMP,
    `date_updated`              timestamp ON UPDATE CURRENT_TIMESTAMP,
    `contact_id`                bigint             DEFAULT NULL,
    `sponsor_id`                bigint             DEFAULT NULL,
    `chapter_id`                int                DEFAULT NULL,
    `parish_id`                 int                DEFAULT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (contact_id) REFERENCES members (id),
    FOREIGN KEY (sponsor_id) REFERENCES members (id),
    FOREIGN KEY (chapter_id) REFERENCES chapter_info (id),
    FOREIGN KEY (parish_id) REFERENCES parish (id),
    FOREIGN KEY (country_id) REFERENCES country (id),
    FOREIGN KEY (education_id) REFERENCES education_level (id)
);